{
 "title": "I2oT-Energy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Battery\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Soc\" or r[\"_field\"] == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Battery\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PvString\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"sunnytripower10se\" or r[\"device_name\"] == \"sunnytripower4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Current\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Exported Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"hausanschluss\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"EnergyIn\")\r\n  |> map(fn: (r) => ({r with _value: r._value /3600}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PvString\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"sunnytripower10se\" or r[\"device_name\"] == \"sunnytripower4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Voltage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "EnergySources",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"EnergyOut\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"meter_004\" or r[\"device_id\"] == \"inverter_001\" or r[\"device_id\"] == \"inverter_002\")\r\n  |> map(fn: (r) => ({r with _value: r._value /3600}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Battery\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\" or r[\"_field\"] == \"Soc\")\r\n  |> set(key: \"device_type\", value: \"Power_Bat\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Battery\" or r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power Souces",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"sunnytripower4\" or r[\"device_name\"] == \"sunnytripower10se\" or r[\"device_name\"] == \"hausanschluss\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Battery\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> map(fn: (r) => ({ r with _value: r._value  * -1 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "path": "csv_exports/out.csv",
     "schema": [
      { "name": "Time", "type": "time" },
      { "name": "Power", "type": "number" }
     ],
     "timezone": "Europe/Berlin"
    }
   ]
  },
  {
   "title": "Battery SoC",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Battery\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Soc\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"inverter_002\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power Souces",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"sunnytripower4\" or r[\"device_name\"] == \"sunnytripower10se\" or r[\"device_name\"] == \"hausanschluss\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Battery\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> map(fn: (r) => ({ r with _value: r._value  * -1 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "path": "csv_exports/out.csv",
     "schema": [
      { "name": "Time", "type": "time" },
      { "name": "Power", "type": "number" }
     ],
     "timezone": "Europe/Berlin"
    },
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "path": "predictions/pv.csv",
     "schema": [
      { "name": "Time", "type": "time" },
      { "name": "Energy_Diff", "type": "number" }
     ],
     "timezone": "Europe/Berlin"
    },
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "path": "predictions/consumption.csv",
     "schema": [
      { "name": "Time", "type": "time" },
      { "name": "Forecast", "type": "number" }
     ],
     "timezone": "Europe/Berlin"
    }
   ]
  },
  {
   "title": "Power Souces",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"sunnytripower4\" or r[\"device_name\"] == \"sunnytripower10se\" or r[\"device_name\"] == \"hausanschluss\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Battery\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> map(fn: (r) => ({ r with _value: r._value  * -1 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "path": "csv_exports/out.csv",
     "schema": [
      { "name": "Time", "type": "time" },
      { "name": "Power", "type": "number" }
     ],
     "timezone": "Europe/Berlin"
    },
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "path": "predictions/pv.csv",
     "schema": [
      { "name": "Time", "type": "time" },
      { "name": "Energy_Diff", "type": "number" }
     ],
     "timezone": "Europe/Berlin"
    },
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "path": "predictions/consumption.csv",
     "schema": [
      { "name": "Time", "type": "time" },
      { "name": "Forecast", "type": "number" }
     ],
     "timezone": "Europe/Berlin"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "query": "buero = from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"meter_001\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      },
      {
       "query": "keller = from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"meter_002\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      },
      {
       "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"meter_003\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      },
      {
       "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> filter(fn: (r) => r[\"device_name\"] == \"sunnytripower4\" or r[\"device_name\"] == \"sunnytripower10se\" or r[\"device_name\"] == \"hausanschluss\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      },
      {
       "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Battery\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Power Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 27 },
     "targets": [
      {
       "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Power\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"meter_003\" or r[\"device_id\"] == \"meter_002\" or r[\"device_id\"] == \"meter_001\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Hausanschluss",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 5, "x": 4, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "query": "from(bucket: \"energydata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"EnergyMeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"EnergyIn\" or r[\"_field\"] == \"EnergyOut\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"meter_004\")\r\n  |> map(fn: (r) => ({r with _value: r._value /3600}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 1, "y": 45 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "path": "predictions/pv.csv",
     "schema": [
      { "name": "Time", "type": "time" },
      { "name": "Energy_Diff", "type": "number" }
     ],
     "timezone": "Europe/Berlin"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 45 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "path": "predictions/consumption.csv",
     "schema": [
      { "name": "Time", "type": "time" },
      { "name": "Forecast", "type": "number" }
     ],
     "timezone": "Europe/Berlin"
    }
   ]
  }
 ]
}